src/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :lunch_events do
    resources :create_event, only: %i[index create]
    resources :create_groups, only: %i[index create]
    resources :allocate_groups, only: %i[index create]
    resources :allocated_groups, only: %i[index]
  end

  resources :lunch_events, only: %i[index show]
  resources :groups, only: %i[index show]
end

src/app/models/lunch_events/group.rb
# frozen_string_literal: true

module LunchEvents
  # class LunchEvents::Group
  #
  # This class is responsible for creating groups for a lunch event.
  class Group < ApplicationRecord
    belongs_to :leader, class_name: 'Person', foreign_key: 'leader_id'
    belongs_to :lunch_event

    has_many :group_memberships, dependent: :destroy, class_name: LunchEvents::Groups::Membership.name

    validates :leader, :lunch_event, presence: true

    def allocatable?
      group_memberships.size.zero? # rubocop:disable Style/ZeroLengthPredicate
    end
  end
end

src/app/models/lunch_events/groups.rb
module LunchEvents::Groups
  def self.table_name_prefix
    "lunch_events_groups_"
  end
end

src/app/models/lunch_events/groups/membership.rb
# frozen_string_literal: true

module LunchEvents
  module Groups
    # class LunchEvents::Groups::Membership
    #
    # This class is responsible for creating a membership between a group and a member.
    class Membership < ApplicationRecord
      belongs_to :member, class_name: Person.name, foreign_key: 'member_id'
      belongs_to :group, class_name: LunchEvents::Group.name, foreign_key: 'group_id'

      validates :group, :member, presence: true
    end
  end
end

src/app/controllers/groups_controller.rb
# frozen_string_literal: true

# class GroupsController
#
# This class is responsible for displaying groups for a lunch event.
class GroupsController < ApplicationController
  def index
    @groups = LunchEvents::Group.includes(:lunch_event, :leader).last(12)
  end

  def show
    @group = LunchEvents::Group.find(params[:id])
    @user_ids = Person.ids
  end
end

src/app/views/groups/_list.html.erb
<%= turbo_frame_tag 'groups' do %>
  <%= link_to 'Create groups', lunch_events_create_groups_path, data: { turbo: true } %>

  <% @groups.present? && @groups.each do |group| %>
    <p>
      <%= group.lunch_event.venue.name %>
      <%= link_to group.lunch_event.scheduled_at, group_path(group), data: { turbo: true } %>
      leader
      <%= group.leader.id %>
    </p>
  <% end %>
<% end %>

src/app/views/groups/index.html.erb
<h2>Groups</h2>
<%= turbo_frame_tag 'groups' do %>
  <%= render partial: 'list', locals: { groups: @groups } %>
<% end %>

src/app/views/groups/show.html.erb
<%= turbo_frame_tag "groups" do %>
  <h2>
    Join lunch event group
  </h2>

  <%= form_with url: group_url do |form| %>
    <p>
      In order to join the lunch event group, please select your user id
    </p>
    <%= form.label :user_id %>
    <%= form.select :user_id, @user_ids %>
    <%= form.submit %>
  <% end %>

  <%= link_to 'Join', group_path(@group), method: :post %>
  <%= link_to 'Cancel', lunch_events_path %>
<% end %>